// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgGp1VqW2bGM4fazIn_glPJFggbxlgT0Q',
    appId: '1:1024967378878:web:1988e4251d91344c841bef',
    messagingSenderId: '1024967378878',
    projectId: 'gaulhidroponik',
    authDomain: 'gaulhidroponik.firebaseapp.com',
    databaseURL: 'https://gaulhidroponik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gaulhidroponik.firebasestorage.app',
    measurementId: 'G-88BMM3P93B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCGyZudvuSeUq3xXDtQbNQ9xF9OMeFhnU',
    appId: '1:1024967378878:android:140ea9ceeefdebf8841bef',
    messagingSenderId: '1024967378878',
    projectId: 'gaulhidroponik',
    databaseURL: 'https://gaulhidroponik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gaulhidroponik.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgGp1VqW2bGM4fazIn_glPJFggbxlgT0Q',
    appId: '1:1024967378878:web:546a7be595bdab3a841bef',
    messagingSenderId: '1024967378878',
    projectId: 'gaulhidroponik',
    authDomain: 'gaulhidroponik.firebaseapp.com',
    databaseURL: 'https://gaulhidroponik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gaulhidroponik.firebasestorage.app',
    measurementId: 'G-7WQ8J6L4BJ',
  );
}
