// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb4Pzbc75EjxsENHkNVjsQf_DbKGNyNF0',
    appId: '1:238476720174:web:8d4d7370dc620d80b687bf',
    messagingSenderId: '238476720174',
    projectId: 'hidroponiktkkc',
    authDomain: 'hidroponiktkkc.firebaseapp.com',
    storageBucket: 'hidroponiktkkc.firebasestorage.app',
    measurementId: 'G-1FK6MCZYEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHEBe1GwBfQe4nYmdGdgmmk3nStYLlVCw',
    appId: '1:238476720174:android:b21783e4a203312cb687bf',
    messagingSenderId: '238476720174',
    projectId: 'hidroponiktkkc',
    storageBucket: 'hidroponiktkkc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPj1TdwaMvIZAUARsO7R_szFT0OLBk1lo',
    appId: '1:238476720174:ios:76058ff8b51798a5b687bf',
    messagingSenderId: '238476720174',
    projectId: 'hidroponiktkkc',
    storageBucket: 'hidroponiktkkc.firebasestorage.app',
    iosBundleId: 'com.example.hidroponiktkkc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPj1TdwaMvIZAUARsO7R_szFT0OLBk1lo',
    appId: '1:238476720174:ios:76058ff8b51798a5b687bf',
    messagingSenderId: '238476720174',
    projectId: 'hidroponiktkkc',
    storageBucket: 'hidroponiktkkc.firebasestorage.app',
    iosBundleId: 'com.example.hidroponiktkkc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb4Pzbc75EjxsENHkNVjsQf_DbKGNyNF0',
    appId: '1:238476720174:web:0fa036cacdc56187b687bf',
    messagingSenderId: '238476720174',
    projectId: 'hidroponiktkkc',
    authDomain: 'hidroponiktkkc.firebaseapp.com',
    storageBucket: 'hidroponiktkkc.firebasestorage.app',
    measurementId: 'G-4E84F40WRC',
  );
}
